### ISSUE TITLE
Decide on parsing library for Scheme parser

### ISSUE THREAD

**Issue by hawkw** [hawkw/seax#22]
I've found a handful of libraries for Rust that provide parsing expression grammars (a.k.a. parser-combinators), my preferred method of writing a parser.
- [`rust-peg`](https://github.com/kevinmehall/rust-peg) by @kevinmehall
- [`nom`](https://github.com/Geal/nom/) by @Geal
- [`rparse`](https://github.com/jesse99/rparse) by @jesse99

Other options (non-PEG) include:
- [`parseil`](https://github.com/shepmaster/peresil) by @shepmaster (this looks very incomplete)
- [`rust-scan`](https://github.com/DanielKeep/rust-scan/) by @DanielKeep (lexer-only)
- Writing the parser/lexer with `lex`/`flex` and `yacc` and linking in the compiled C code using Rust FFI.
  As my dislike of `yacc` is rather well-known, I think that it's fairly obvious that I am Not Going To Do This.

**Comment by hawkw** [comment]
After some preliminary research, it looks like `rust-peg` and `nom` are likely the most stable and complete libraries. I'll keep looking into both of them.

**Comment by hawkw** [comment]
A quick [search on crates.io](https://crates.io/crates/parser-combinators) reveals that there's also the creatively named [`parser-combinators`](https://github.com/Marwes/parser-combinators) library by @Marwes

**Comment by Geal** [comment]
Feel free to ping me if you have any questions about nom. This library is more oriented towards file and network format parsing, so a lexer made for languages might be more practical. But I think nom can handle it :smiley:

**Comment by hawkw** [comment]
> This library is more oriented towards file and network format parsing

Yeah, I got that sense looking at your documentation. With that said, your library is one of the most well-documented and feature complete of the ones I've found, so I may end up using it anyway. 

Scheme isn't a hard language to parse, anyway (a handwritten regex parser would probably work just fine, I just like PEG), so it should work just fine. If I do run into any hangups, I won't hesitate to let you know, though. Thanks for dropping in!

**Comment by hawkw** [comment]
I think I'm going to go with `nom` for now, since  while the `rust-peg` library is also cool, `nom` seems better documented and isn't generating a parser from an external library file (which gives me painful `yacc` flashbacks).

**Comment by shepmaster** [comment]
@hawkw thanks for inspiring me to finally write some tests and documentation! ^_^ I hope nom works well for you!

**Comment by hawkw** [comment]
@shepmaster no problem! Your library looks really nifty, I just couldn't figure out how to use it. :)

**Comment by shepmaster** [comment]
@hawkw I'm working on v0.2.0 now. v0.1.0 was mostly extracted from my other projects, and so didn't have any tests or documentation. v0.2.0 is being test-driven and should have API docs and examples. Maybe I'll peek at nom to learn how to Do It Right. :smiley_cat:

**Comment by Marwes** [comment]
@hawkw Any thoughts on parser-combinator? Considering it is to parsec what nom is to attoparsec I'm a bit curious why you decided against it?

**Comment by hawkw** [comment]
@Marwes Ah, I think that the main reason I passed over parser-combinator was that I couldn't find the docs. Looking back at your repo I see that there's a link in the README that I must have overlooked. My bad. I'll take a closer look - it might indeed be better for my purposes, as I'd really prefer to use a parsing library intended for user facing language parsing.

I really appreciate how the creators of most of the libraries I've been looking at have taken the time to comment on this issue - that's definitely something awesome about the Rust community.

**Comment by hawkw** [comment]
Okay, @Marwes, I have a stupid question about parser-combinator: How do I parse one parser followed by a different parser? There's a struct for the [`And`](http://marwes.github.io/parser-combinators/doc/parser-combinators/combinator/struct.And.html) combinator but no function for it, and the documentation never really explains exactly how to use it.

**Comment by Marwes** [comment]
Its in the [ParserExt](http://marwes.github.io/parser-combinators/doc/parser-combinators/trait.ParserExt.html) trait there are a few parsers hidden there for those that make more sense to chain one after the other. Guess I might need to hint towards it in the main page.

**Comment by hawkw** [comment]
@Marwes Oh, yeah, there it is. Thanks a lot. 

`parser-combinator` took a little getting used to (I'm more familiar with Scala's parser combinators implementation than I am with `parsec`) but I think I've got it figured out now. Thanks for writing the library and for your advice!
